FROM ubuntu:16.04

# Install tools and dependencies
RUN dpkg --add-architecture i386
RUN apt-get update
RUN echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections
RUN apt-get install -y --no-install-recommends apt-utils
RUN apt-get install -y --no-install-recommends \
    binutils \
    automake \
    git \
    ca-certificates \
    wget \
    curl \
    python \
    libc6:i386 \
    libncurses5:i386 \
    libstdc++6:i386 \
    build-essential \
    g++-4.8-multilib \
    libboost-dev \
    libsqlite3-dev \
    zlib1g-dev \
    libbz2-dev \
    g++-4.8

WORKDIR /root
RUN git clone http://snipersim.org/download/85e5294d35db5c40/git/sniper.git && \
    cd sniper && \
    wget -nv --no-check-certificate https://software.intel.com/sites/landingpage/pintool/downloads/pin-3.7-97619-g0d0c92f4f-gcc-linux.tar.gz && \
    tar -xzf pin-3.7-97619-g0d0c92f4f-gcc-linux.tar.gz && \
    mv pin-3.7-97619-g0d0c92f4f-gcc-linux pin_kit && \
    rm pin-3.7-97619-g0d0c92f4f-gcc-linux.tar.gz

COPY sniper-7.1-shmemperf-and-maxthreads-fix-v2.patch .
RUN patch -p1 sniper-7.1-shmemperf-and-maxthreads-fix-v2.patch

RUN cd /root/sniper && \
    make