FROM ubuntu:16.04

# Install tools and dependencies
RUN dpkg --add-architecture i386
RUN apt-get update
RUN echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections
RUN apt-get install -y --no-install-recommends apt-utils
RUN apt-get install -y --no-install-recommends \
    binutils \
    automake \
    git \
    ca-certificates \
    wget \
    curl \
    python \
    libc6:i386 \
    libncurses5:i386 \
    libstdc++6:i386 \
    build-essential \
    g++-4.8-multilib \
    libboost-dev \
    libsqlite3-dev \
    zlib1g-dev \
    libbz2-dev \
    g++-4.8

WORKDIR /root
ENV CC=/usr/bin/gcc-4.8
ENV CXX=/usr/bin/g++-4.8
RUN wget http://snipersim.org/download/85e5294d35db5c40/packages/sniper-6.1.tgz && \
    tar -xzf sniper-6.1.tgz && \
    mv sniper-6.1 sniper && \
    cd sniper && \
    wget -nv --no-check-certificate https://software.intel.com/sites/landingpage/pintool/downloads/pin-2.14-71313-gcc.4.4.7-linux.tar.gz && \
    tar -xzf pin-2.14-71313-gcc.4.4.7-linux.tar.gz && \
    mv pin-2.14-71313-gcc.4.4.7-linux pin_kit && \
    rm pin-2.14-71313-gcc.4.4.7-linux.tar.gz

RUN cd /root/sniper && \
    make